services:

    data_base_l02_dza:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: data_base_l02_dza
        expose:
            - 1433
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "#sa123456"
            ACCEPT_EULA: "Y" 
            MSSQL_PID: "Express"
        networks:
            - l02-dza-network

    l02_dza_api:
        container_name: l02_dza_api
        build:
            context: ./src
            dockerfile: Dockerfile
        environment:
            ASPNETCORE_ENVIRONMENT: Stage
            ASPNETCORE_HTTP_PORTS: "80"
            #ASPNETCORE_URLS: http://+:80
            #ASPNETCORE_URLS: https://+:443;http://+:80
            USE_HTTPS_REDIRECTION: "false"
        restart: always
        ports:
            - "8082:80"
            #- "443:443"
        networks:
            - l02-dza-network
        depends_on:
            - data_base_l02_dza
        
networks:
    l02-dza-network:
        driver: bridge