services:
    api-demo:
        image: L02_DZA_API:latest
        container_name: L02_DZA_API
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            ASPNETCORE_ENVIRONMENT: Development
        restart: always
        ports:
            - "8080:8080"