services:
    l01_dza_api:
        container_name: l01_dza_api
        build:
            context: ./src
            dockerfile: Dockerfile
        environment:
            ASPNETCORE_ENVIRONMENT: Development
        restart: always
        ports:
            - "8082:8080"