services:
    l02_dza_api:
        container_name: l02_dza_api
        build:
            context: ./src
            dockerfile: Dockerfile
        environment:
            ASPNETCORE_ENVIRONMENT: Development
        restart: always
        ports:
            - "8082:8080"
        networks:
            - l02-dza-network
        depends_on:
            - data_base_l02_dza

    data_base_l02_dza:
        container_name: data_base_l02_dza
        build: 
            context: ./src/DataBase
            dockerfile: Dockerfile
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "#sa123456"
            ACCEPT_EULA: "Y"
        networks:
            - l02-dza-network
        
networks:
    l02-dza-network:
        driver: bridge